version: '3.8'

services:
  app:
    build:
      context: .  # Usa el Dockerfile en el directorio actual
      dockerfile: Dockerfile
    container_name: calculate_app  # Nombre del contenedor
    ports:
      - "3000:3000"  # Expone el puerto 3000 (ajusta según tu aplicación)
    environment:
      - NODE_ENV=development  # Establece el entorno
    networks:
      - app-network

networks:
  app-network:
    driver: bridge