version: '3.8'

services:
  calculate_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculate_app
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    command: >
      sh -c "pnpm build && pnpm start"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge